### PR TITLE
feat: tup 648 do not use plain highlight class

### PR DESCRIPTION
**Pull request by wesleyboar**
## Overview

Use `.u-highlight` not `.highlight`.

> **Warning**
> Merge delayed; pending https://github.com/TACC/Core-Styles/pull/261.

> **Important**
> After deploy:
> 1. Replace use of `highlight` class with `u-highlight` in snippet.
> 2. Replace use of `highlight` class with `u-highlight` in markup.
> 3. Test again.
> 4. Publish
>
> <details><summary>screenshot guides</summary>
>
> | | Before | After |
> | - | - | - |
> | markup | markup BEFORE | markup AFTER |
> | snippet | snippet BEFORE | snippet AFTER |
>
> </details>

## Related

- [TUP-648](https://jira.tacc.utexas.edu/browse/TUP-648)
- expects https://github.com/TACC/Core-Styles/pull/261

## Changes

- **changed** CSS in a CMS snippet
- **changed** CSS in a CMS stylesheet

## Testing

1. Mimic changes from https://github.com/TACC/Core-Styles/pull/261.
2. Load styles from this #370 PR.
3. Edit markup of banner text to use `u-highlight`, not `highlight`.
4. Verify header text is highlighted the same as before.
5. Verify header text — on hover — is highlighted the same as before.

## UI

| changed markup and css, annotated screenshot |
| - |
| annotated screenshot |

| changed markup and css, mouse hover screenshot |
| - |
| screenshot on hover |

### CODE REVIEW

**Review by R-Tomas-Gonzalez — APPROVED** [review]
~~Looks good with core-styles change! Need to test hover effect. Something seems off.~~
Screenshot 2023-11-15 at 1 11 13 PM

~~Ahh, it's coming from the snippets, I must not have loaded that correctly. Should be properly loaded on my end...~~

It works when manually changing the style on the hover. For some reason I must not be building the html properly – something I will talk to @wesleyboar about not on this PR. 

**Approving.**

**Review by R-Tomas-Gonzalez — APPROVED** [review]

**Comment by wesleyboar** [comment]
> **Warning**
> Merge delayed; pending https://github.com/TACC/Core-Styles/pull/261.

**Comment by R-Tomas-Gonzalez** [comment]
> > **Warning**
> > Merge delayed; pending [TACC/Core-Styles#261](https://github.com/TACC/Core-Styles/pull/261).

Adjustments made to PR above ^

**Comment by wesleyboar** [comment]
Tested locally with #344's [90163f6](https://github.com/TACC/tup-ui/pull/344/commits/90163f68b4c68f8773d4f55726b8301f5ec76fe0) merged in ([543cea3](https://github.com/TACC/tup-ui/pull/370/commits/543cea3fcb27f472ebce264bbd7f51fe1c8be0f0). Worked.

**Pull request merged**
