### PR TITLE
fix(tup-ui): manage account, remove redundant text

### PR DESCRIPTION
**Pull request by wesleyboar**
## Overview / Changes

Remove redundant text.

## Related

None.

## Testing:

1. Confirm redundant text is gone from Manage Account page.

## UI

| Before | After |
| - | - |
| before | after |

### CODE REVIEW

**Review by sophia-massie — CHANGES_REQUESTED** [review]
Just needs a format check and LGTM other than that!

**Review by sophia-massie — APPROVED** [review]

**Review by jarosenb — CHANGES_REQUESTED** [review]
The link still says "Go to TAP", could you please change the wording to "TAM" while you're in here?

**Comment by wesleyboar** [comment]
@jarosenb Since merging `main`, the button does not read "Go to TAP". It now has the text from #150, "Edit User Profile".

**Review by jarosenb — APPROVED** [review]
LGTM, didn't realize the TAP thing was already fixed.

**Pull request merged**
